name: Deploy React Ecommerce App

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Stop existing container
        run: |
          docker compose down || true

      - name: Build Docker image
        run: |
          docker compose build

      - name: Start application
        run: |
          docker compose up -d

      - name: Check running containers
        run: |
          docker ps